# question_data = [
#     {"text": "A slug's blood is green.", "answer": "True"},
#     {"text": "The loudest animal is the African Elephant.", "answer": "False"},
#     {"text": "Approximately one quarter of human bones are in the feet.", "answer": "True"},
#     {"text": "The total surface area of a human lungs is the size of a football pitch.", "answer": "True"},
#     {"text": "In West Virginia, USA, if you accidentally hit an animal with your car, you are free to take it home to eat.", "answer": "True"},
#     {"text": "In London, UK, if you happen to die in the House of Parliament, you are entitled to a state funeral.", "answer": "False"},
#     {"text": "It is illegal to pee in the Ocean in Portugal.", "answer": "True"},
#     {"text": "You can lead a cow down stairs but not up stairs.", "answer": "False"},
#     {"text": "Google was originally called 'Backrub'.", "answer": "True"},
#     {"text": "Buzz Aldrin's mother's maiden name was 'Moon'.", "answer": "True"},
#     {"text": "No piece of square dry paper can be folded in half more than 7 times.",
#         "answer": "False"},
#     {"text": "A few ounces of chocolate can to kill a small dog.", "answer": "True"}
# ]


question_data = [{"category": "General Knowledge", "type": "boolean", "difficulty": "easy", "question": "Gumbo is a stew that originated in Louisiana.", "correct_answer": "True", "incorrect_answers": ["False"]}, {"category": "History", "type": "boolean", "difficulty": "hard", "question": "The Kingdom of Prussia briefly held land in Estonia.", "correct_answer": "False", "incorrect_answers": ["True"]}, {"category": "Geography", "type": "boolean", "difficulty": "medium", "question": "Gothenburg is the capital of Sweden.", "correct_answer": "False", "incorrect_answers": ["True"]}, {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "hard", "question": "In Undertale, having a &quot;Fun Value&quot; set to 56-57 will play the &quot;Wrong Number Song Call&quot;.", "correct_answer": "False", "incorrect_answers": ["True"]}, {"category": "Sports", "type": "boolean", "difficulty": "medium", "question": "The Olympics tennis court is a giant green screen.", "correct_answer": "True", "incorrect_answers": ["False"]}, {"category": "Entertainment: Television", "type": "boolean",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  "difficulty": "easy", "question": "In &quot;Star Trek&quot;, Klingons are aliens.", "correct_answer": "True", "incorrect_answers": ["False"]}, {"category": "Science & Nature", "type": "boolean", "difficulty": "medium", "question": "Sugar contains fat.", "correct_answer": "False", "incorrect_answers": ["True"]}, {"category": "History", "type": "boolean", "difficulty": "easy", "question": "The French Kingdom helped the United States gain their independence over Great Britain during the Revolutionary War.", "correct_answer": "True", "incorrect_answers": ["False"]}, {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "easy", "question": "In the &quot;S.T.A.L.K.E.R.&quot; series, the Freedom faction wishes to destroy the supernatural area known as  &quot;the Zone&quot;.", "correct_answer": "False", "incorrect_answers": ["True"]}, {"category": "Entertainment: Film", "type": "boolean", "difficulty": "hard", "question": "YouTube personality Jenna Marbles served as an executive producer of the film Maximum Ride (2016).", "correct_answer": "True", "incorrect_answers": ["False"]}]
